### ISSUE TITLE
Exception while saving forms

### ISSUE THREAD

**Issue by maikschneider** [r3h6/TYPO3.EXT.form_translator#17]
When saving a form with `validationErrorMessages` in the form builder module, the following error occurs:

```
Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "_originalIdentifier" in /var/www/html/xxxx/vendor/r3h6/form-translator/Classes/Hooks/TranslateValidationErrorMessages.php line 42
```

Example element:

```yaml
      - defaultValue: ''
        type: Email
        identifier: email-1
        label: 'E-Mail Adresse'
        properties:
          fluidAdditionalAttributes:
            required: required
          validationErrorMessages:
            - code: 1221560910
              message: 'Bitte geben Sie eine valide E-Mail Adresse an.'
            - code: 1221560718
              message: 'Bitte geben Sie eine valide E-Mail Adresse an.'
            - code: 1347992400
              message: 'Bitte geben Sie eine valide E-Mail Adresse an.'
            - code: 1347992453
              message: 'Bitte geben Sie eine valide E-Mail Adresse an.'
        validators:
          - identifier: EmailAddress
          - identifier: NotEmpty
```

In this hook there is quite some old stuff, like `->getAttribute('language')`.

TYPO3 v12.4.24, PHP 8.3
